### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by kkarayannis**

### CODE REVIEW

**Comment by kkarayannis** [comment]
Here's what this PR fixes:
Special product tile size when we have 3 tiles.
Removed metric override for GB.
If inches are 0, then use cm
Fixed "Pack of" on the photo selection screen for posters and postcards
Promo banner now disappears when the countdown is done, and does not show up when the countdown date is in the past.
Lower the promo banner a bit more so that the header is also out of view when hiding.
Fixed never transitioning to the next screen if the template sync failed but we had cached/embedded templates.
Product Overview page imageView should clip to bounds, otherwise we get weird issues when scrolling when an image is larger than the screen.
Ask the child view controller for the status bar style.
KiteViewController: Moved subscribing to NSNotificationCenter to viewDidLoad.

**Comment by dbotha** [comment]
@kkarayannis KiteViewController seems to take forever to load sometimes (10+ seconds), maybe 1/5 times, I think something is definitely up here. When it does load it's like lightning though and noticeably improved over current live PicCollage.

I see the following in the console occasionally although this is unrelated:

2015-08-10 11:22:57.044 KitePrintSDK[237:7469] Warning: Attempt to present <UIAlertController: 0x13756d150> on <OLKiteViewController: 0x1375705c0> whose view is not in the window hierarchy!

**Comment by dbotha** [comment]
@kkarayannis the above issue does not occur at all on master so it's definitely introduced on this branch

**Comment by kkarayannis** [comment]
I made a small tweak that I believe solves the issue where it takes forever to load. Let me know if it's still a problem.

**Pull request merged**
